#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#
#-------------------------------------------------------------------------------#
#            Discover all capabilities of Qodana in our documentation           #
#             https://www.jetbrains.com/help/qodana/about-qodana.html           #
#-------------------------------------------------------------------------------#

name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          project-path: .
          output-path: ./qodana-results
          cache-path: ./qodana-cache
          image: jetbrains/qodana-jvm-community:2025.3
          pr-mode: false
          use-caches: true
          post-pr-comment: true
          use-annotations: true
          upload-result: true
          push-fixes: 'none'